name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Lambda dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r lambdas/requirements.txt
          # pytest tests/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.12.2'

      - name: Terraform Init & Validate
        working-directory: ./infra
        run: |
          terraform init -input=false
          terraform validate

      # Configure AWS credentials (scoped to deploy steps)
      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Deploy Terraform infrastructure
      - name: Deploy Terraform infrastructure
        if: github.ref == 'refs/heads/main'
        working-directory: ./infra
        run: terraform apply -auto-approve

      # Deploy SAM Lambda
      - name: Deploy SAM application
        if: github.ref == 'refs/heads/main'
        run: ./deploy-sam.sh


      # Optional: Build and deploy React frontend
      # - name: Build and deploy React frontend
      #   run: |
      #     cd frontend
      #     npm ci
      #     npm run build
      #     aws s3 sync build/ s3://your-frontend-bucket-name
